title: LeelaMadhav Somu
logo: download (5).png
 description: Ai / ML / Deep Learning / xAi
show_downloads: true
theme: jekyll-theme-minimal
[Download Resume](/path/to/your/resume.pdf) | [View On GitHub](https://github.com/yourusername/yourrepo)



