
---
title: LeelaMadhav Somu
logo: download (5).png
description: Ai / ML / Deep Learning / xAi
show_downloads: true
theme: jekyll-theme-minimal
---

[Download Resume](https://mavsuta-my.sharepoint.com/:w:/r/personal/lxs8333_mavs_uta_edu/Documents/data_science%20resume.docx?d=w9b7a326f67884f42b676370550dae40f&csf=1&web=1&e=SMgl6V) | [View On GitHub](https://github.com/SomuLeelaMadhav/PortFolio)




